- name: 配置nginx yum源
  yum_repository:
    name: nginx
    description: nginx repo
    file: nginx
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgcheck: no
    mode: 0644
    state: present

- name: 安装nginx
  yum: name=nginx state=present

# 解决访问dss报403的问题
- name: 配置nginx
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '^user'
    line: 'user root;'

- name: 启动nginx服务
  systemd: name=nginx enabled=yes daemon_reload=yes state=restarted
  tags:
    - restart

- name: 更新首页信息
  template:
    src: "index.html.j2"
    dest: "/usr/share/nginx/html/index.html"

- name: 测试访问nginx
  uri:
    url: http://127.0.0.1
    return_content: yes
    status_code: 200
  register: curl_info

- name: 打印请求信息
  debug: var=curl_info.msg