- name: 安装Development tools
  yum:
    name: "@Development tools"
    state: present

- name: 安装依赖包
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - gdbm-devel
    - libpcap-devel
    - xz-devel
    - libffi-devel

- name: 解压源码包
  shell:
    chdir: /tmp/
    cmd: "tar xf {{ WORKSPACE_HOME }}/download/Python-3.7.0.tar.xz"

- name: 配置python3
  shell:
    chdir: /tmp/Python-3.7.0
    cmd: "./configure --prefix=/usr/local/python3"

- name: 编译安装python3
  shell:
    chdir: /tmp/Python-3.7.0
    cmd: "make && make install"

- name: 设置python3软连接
  file:
    src: /usr/local/python3/bin/python3
    dest: /usr/bin/python3
    state: link

- name: 检查pip3是否已存在
  stat: path=/usr/bin/pip3
  register: pip3_stat

- name: 移除原pip3
  command: mv /usr/bin/pip3 /usr/bin/pip3.bak
  when: pip3_stat.stat.exists

- name: 设置pip3软连接
  file:
    src: /usr/local/python3/bin/pip3
    dest: /usr/bin/pip3
    state: link
    force: yes

- name: 获取python3版本信息
  command: "python3 -V"
  register: python3_version

- name: 打印python3版本
  debug: var=python3_version