- name: 设置python软连接
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link

- name: 获取python3版本信息
  command: "python3 -V"
  register: python3_version

- name: 打印python3版本
  debug: var=python3_version
